#!/bin/bash
set -e

INPUT=$1
OUTPUT=$2
QUALITY=${3:-'90'}

ISO=$(exiftool "$INPUT" -t -ISO | cut -f2)

echo "Converting $INPUT to $OUTPUT..." >&2

dcraw -w -c -b ${4:-1} -H 0 -T "$INPUT" | \
  nice magick - \
    -wavelet-denoise $ISO \
    -modulate '100,120' \
    -contrast-stretch '0.3x0%' \
    -level '0%,100%,1.2' \
    -sigmoidal-contrast '2.50,50%' \
    -adaptive-sharpen '0x4.0' \
    -quality $QUALITY -auto-orient \
  "$OUTPUT"

echo "Rewriting Exif..." >&2

exiftool -overwrite_original -TagsFromFile "$INPUT" "$OUTPUT"
